#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/uer/bin
LD_LIBPARY_PATH=$LD_LIBPARY_PATH:/lib:/usr/lib
export PATH LD_LIBPARY_PATH                         # runlevel


mount -a
mkdir /dev/pts
mount -t devpts devpts /dev/pts

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
